export enum DDBType {
  MEDIA = 'MEDIA',
  GAME = 'GAME',
  GUIDE = 'GUIDE',
  GUIDE_SECTION = 'GUIDE_SECTION',
  GUIDE_ITEM = 'GUIDE_ITEM',
  ACCOUNT_GUIDE = 'ACCOUNT_GUIDE',
  ACCOUNT_GUIDE_ITEM = 'ACCOUNT_GUIDE_ITEM',
}
