import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { signIn, useSession } from 'next-auth/react';

import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const session = useSession();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to{' '}
          <a href="https://game-progress-tracker.atlassian.net/wiki/spaces/MAIN/pages/163939/Introduction">
            Game Progress Tracker!
          </a>
        </h1>

        <pre>
          <code>{JSON.stringify(session, null, 5)}</code>
        </pre>

        <button onClick={() => signIn()}>Sign In</button>
      </main>
    </div>
  );
};

export default Home;
